### ISSUE TITLE
My automatic blog deploy broke again

### ISSUE THREAD

**Issue by posix4e** [ipfs-shipyard/ipfs-deploy#149]
https://github.com/posix4e/blog
uses
https://travis-ci.org/github/posix4e/blog
to deploy my site and it's failing with
```
Total in 14 ms
The command "git submodule sync && git submodule update && hugo" exited with 0.
33.42s$ xvfb-run ./deploy.sh
+npm install -g ipfs-deploy
/home/travis/.nvm/versions/node/v8.12.0/bin/ipfs-deploy -> /home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/ipfs-deploy/bin/ipfs-deploy.js
/home/travis/.nvm/versions/node/v8.12.0/bin/ipd -> /home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/ipfs-deploy/bin/ipfs-deploy.js
> secp256k1@3.8.0 install /home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/ipfs-deploy/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."
> secp256k1@3.8.0 rebuild /home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/ipfs-deploy/node_modules/secp256k1
> node-gyp rebuild
make: Entering directory '/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/ipfs-deploy/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
  CXX(target) Release/obj.target/secp256k1/src/privatekey.o
../src/privatekey.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE privateKeyNegate(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/privatekey.cc:73:61: warning: ignoring return value of ‘int secp256k1_ec_privkey_negate(const secp256k1_context*, unsigned char*)’, declared with attribute warn_unused_result [-Wunused-result]
   secp256k1_ec_privkey_negate(secp256k1ctx, &private_key[0]);
                                                             ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-nonnull-compare’
  CXX(target) Release/obj.target/secp256k1/src/publickey.o
  CXX(target) Release/obj.target/secp256k1/src/signature.o
  CXX(target) Release/obj.target/secp256k1/src/ecdsa.o
  CXX(target) Release/obj.target/secp256k1/src/ecdh.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/src/secp256k1.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_parsing.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_privatekey_parsing.o
  SOLINK_MODULE(target) Release/obj.target/secp256k1.node
  COPY Release/secp256k1.node
make: Leaving directory '/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/ipfs-deploy/node_modules/secp256k1/build'
> ursa-optional@0.10.1 install /home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/ipfs-deploy/node_modules/ursa-optional
> node rebuild.js
+ ipfs-deploy@7.14.0
added 434 packages from 399 contributors in 31.801s
+ipfs-deploy -p infura -p pinata -d cloudflare
/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/ipfs-deploy/node_modules/dnslink-cloudflare/lib/index.js:3
async function * browse (api, data, ...args) {
               ^
SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v8.12.0/
```

**Comment by hacdias** [comment]
I see you're using Node 8. The latest released version (8) requires Node 10+. The next version will require Node 14+. Upgrading the Node version on CI will fix the problem.
