### ISSUE TITLE
Promise error pinning to Pinata

### ISSUE THREAD

**Issue by Evanito** [ipfs-shipyard/ipfs-deploy#198]
Started happening recently, unable to use ipfs-deploy anymore for pinning my website to Pinata.
Logs below.

```
- 📦  Calculating size of cluster…
√ 🚚  Directory cluster weighs 3.7 KiB.
- 📠  Uploading and pinning to Pinata…
(node:23608) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (C:\Users\Evan\AppData\Roaming\npm\node_modules\ipfs-deploy\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Evan\AppData\Roaming\npm\node_modules\ipfs-deploy\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Evan\AppData\Roaming\npm\node_modules\ipfs-deploy\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:23608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Evanito** [comment]
Found issue right away, had removed my card from Pinata and it started rejecting my pins due to being over the billing rate. 
This is not a critical issue, just could print the error better.
Closing
