### ISSUE TITLE
HTTPError: project id required

### ISSUE THREAD

**Issue by maxdesalle** [ipfs-shipyard/ipfs-deploy#239]
Getting the following error when trying to push a folder to IPFS with the `ipd <folder-name>` command:
```
📂  Deploying build directory.
📦  Calculating size of build…
🚚  Directory build weighs 7.2 MiB.
⚙️   Validating pinners configurations…
⚙️   Validating DNS providers configurations…
📠  Uploading and pinning to Infura…
❌  An error has occurred:

HTTPError: project id required

    at Object.errorHandler [as handleError] (/usr/local/lib/node_modules/ipfs-deploy/node_modules/ipfs-http-client/src/lib/core.js:100:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.fetch (/usr/local/lib/node_modules/ipfs-deploy/node_modules/ipfs-utils/src/http.js:145:9)
    at async Object.addAll (/usr/local/lib/node_modules/ipfs-deploy/node_modules/ipfs-http-client/src/add-all.js:40:17)
    at async all (/usr/local/lib/node_modules/ipfs-deploy/node_modules/it-all/index.js:12:20)
    at async Infura.pinDir (/usr/local/lib/node_modules/ipfs-deploy/src/pinners/ipfs-node.js:26:22)
    at async pinCidOrDir (/usr/local/lib/node_modules/ipfs-deploy/src/deploy.js:50:17)
    at async deploy (/usr/local/lib/node_modules/ipfs-deploy/src/deploy.js:252:17)
    at async main (/usr/local/lib/node_modules/ipfs-deploy/src/cli.js:169:5)
```

Using NodeJS version `v16.4.0`.

**Comment by besoeasy** [comment]
Infura now requires project ID

nothing devs can do

**Comment by ekumahost** [comment]
so how do we add our project id. to this script to continue working

**Comment by websoftwares** [comment]
Hello @maxdesalle

I was successfully able to pin to Infura, all I had to do was create a .env file and store the project id and secret

See the readme docs here: https://github.com/ipfs-shipyard/ipfs-deploy/blob/master/md/usage.md#pinning-services-configuration

/CC @besoeasy @ekumahost
